export const FETCH_POKEMON_BEGIN = 'FETCH_POKEMON_BEGIN';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE';
export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS';
export const SEARCH_POKEMON_FAILURE = 'SEARCH_POKEMON_FAILURE';